### ISSUE TITLE
バージョンを超えてマルチプレイ (1.1.0 - 1.2.6) の本家のリクエストを導入しますか？

### ISSUE THREAD

**Issue by tomo0611** [MBE-ServerProject/Nukkit-JP#2]
https://github.com/Nukkit/Nukkit/pull/1963

**Comment by MBE-ServerProject** [comment]
現在、Nukkit-JPではバージョン1.2を基準に互換性を重視した開発が進められています。
クロスバージョンの導入は、一定の開発が進んだ頃に視野に入れていきたいと思います。
よろしくお願いします。

**Comment by tomo0611** [comment]
お返事ありがとうございます
了解しました
